#!/usr/bin/env bash
hex() { xxd | awk '{ $1 = ""; print $0 }'; }
hex() { xxd; }
sgott() { ./sgott.js; }

if [ "$1" = "" ]; then
  echo File not specified!
  exit 1
fi

if [ "$2" = "hexdiff" ]; then
  vimdiff \
   <( hex < $1 ) \
   <( sgott < $1 | sgott | hex )
elif [ "$2" = "jsondiff" ]; then
  vimdiff \
   <( sgott < $1 ) \
   <( sgott < $1 | sgott | sgott )
elif [ "$2" = "result" ]; then
   sgott < $1 | sgott | hex
else
  hex < $1
fi


