const colors = [
  'Red',
  'Green',
  'Blue',
  'Alpha',
]
const vector = [
  'X',
  'Y',
  'Z',
]

const soundEffect = [
  null,
  'SoundName',
]

const ammoClasses = {
  BombBullet01: [
    'IsMobile',
    'IsDetector',
     null,
     'PrimerDelay',
     null,
     'LedPosition',
     'BombExplosionType',
     'SplendorParameters',
  ],
  MissileBullet02: [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'FireSe',
    null,
    null,
    null,
    'SubMissiles',
  ],
  SentryGunBullet01: [
    null,
    null,
    null,
    null,
    'SearchRange',
    'TurnSpeed',
    null,
    null,
    'AmmoClass',
    'AmmoCount',
    'AmmoSize',
    'Ammo_CustomParameter',
    'FireSe',
  ],
}

const names = {
  ammoClasses: ammoClasses,
  AmmoColor: colors,
  LedPosition: colors,
  SplendorParameters: [
    'FlechetteSpread',
    'SearchRange',
    'FlechetteCount',
    'FlechetteAlive',
    'FlechetteSpeed',
    'FlechetteSize',
  ],
  FlechetteSpread: [
   'Horizontal',
   'Vertical',
   'VerticalOffset',
 ],
 SubMissiles: [
   null,
   null,
   'SubAmmoCount',
   null,
   'AmmoClass',
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   'AmmoColor',
   'Ammo_CustomParameter',
   'ModelName',
   null,
   null,
   null,
   'FireSe',
   'MuzzleFlash',
   'MuzzleFlash_CustomParameter',
 ],
 AmmotHitSe: soundEffect,
 FireSe: soundEffect,
 name: [
   'Japanese',
   'English',
   'Chinese',
 ],
 resource: [
   'path',
 ],
}

const ammoClassOptions = [
  'LightningBullet01',
  'LaserBullet01',
  'LaserBullet02',
  'LaserBullet03',
  'FlameBullet01',
  'FlameBullet02',
  'SpiderStringBullet01',
  'SpiderStringBullet02',
  'ShockWaveBullet01',
  'SlashWaveBullet01',
  'HomingLaserBullet01',
  'BeamBullet01',
  'DecoyBullet01',
  'NeedleBullet01',
  'BarrierBullet01',
  'ClusterBullet01',
  'AcidBullet01',
  'NapalmBullet01',
  'GrenadeBullet01',
  'MissileBullet01',
  'MissileBullet02',
  'RocketBullet01',
  'RocketBullet02',
  'SolidBullet01',
  'SolidBullet02',
  'SmokeCandleBullet01',
  'ShieldBashBullet01',
  'SentryGunBullet01',
  'TargetMarkerBullet01',
  'SupportUnitBullet01',
  'PileBunkerBullet01',
]

const values = {
  AmmoClass: ammoClassOptions,
  BombExplosionType: [0, 1, 2],
  SecondaryFire_Type: [0, 1, 2, 3],
}

module.exports = {names, values}
